### ISSUE TITLE
Fetching tenant details broken in 2.0.1

### ISSUE THREAD

**Issue by ivan-st** [Azure-Samples/active-directory-dotnet-graphapi-console#9]
The offending line of code is:

```
var tenantsList = (await activeDirectoryClient.TenantDetails
        .Where(tenantDetail => tenantDetail.ObjectId.Equals(TENANT_ID))
        .ExecuteAsync())
    .CurrentPage.ToList();
```

It works however when I downgrade to 2.0.0 version of the NuGet package!

The exception is thrown of type _InvalidOperationException_ with an error message: _A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent._

The stack trace is:
   at System.Data.Services.Client.Materialization.FeedAndEntryMaterializerAdapter.TryRead()
   at System.Data.Services.Client.Materialization.FeedAndEntryMaterializerAdapter.TryStartReadFeedOrEntry()
   at System.Data.Services.Client.Materialization.FeedAndEntryMaterializerAdapter.TryReadFeedOrEntry(Boolean lazy, ODataFeed& feed, MaterializerEntry& entry)
   at System.Data.Services.Client.Materialization.FeedAndEntryMaterializerAdapter.Read()
   at System.Data.Services.Client.Materialization.ODataReaderEntityMaterializer.ReadNextFeedOrEntry()
   at System.Data.Services.Client.Materialization.ODataEntityMaterializer.ReadImplementation()
   at System.Data.Services.Client.Materialization.ODataMaterializer.Read()
   at System.Data.Services.Client.MaterializeAtom.MoveNextInternal()
   at System.Data.Services.Client.MaterializeAtom.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__b1`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.PagedCollection`2..ctor(DataServiceContextWrapper context, QueryOperationResponse`1 qor)
   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<>c__DisplayClass4b`2.<ExecuteAsync>b__49(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<ExecuteAsync>d__4d`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.ReadOnlyQueryableSet`2.<<ExecuteAsync>b__0>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Common.BLL.Accounts.<GetTenantDetailAndActiveDirectoryClient>d__eb.MoveNext() in [..].cs:line 1118

**Comment by bmsandeepkumar** [comment]
I'm getting the same error. I'm using the 2.11 version. Can't find much help on google. Any help is much appreciated.

**Comment by Jontem** [comment]
I also getting this error since an hour ago.

""A value without a type name was found and no expected type is available. When the model is specified, each value in the payload must have a type which can be either specified in the payload, explicitly by the caller or implicitly inferred from the parent value."

**Comment by duongthaiha** [comment]
Yes same problem with me update to 2.0.6 fix it

**Comment by hvaughan3** [comment]
As has already been mentioned, updating `Microsoft.Azure.ActiveDirectory.GraphClient` to 2.0.6 fixed the problem. This was not happening yesterday using version 2.0.5.
